apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eap-app
    app.kubernetes.io/component: eap-app
    app.kubernetes.io/instance: eap-app
  name: eap-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: eap-app    
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: eap-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/oqss-dev/eap-app:latest
        imagePullPolicy: IfNotPresent
        name: eap-app
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
